chore(zsh/bin): Upgrade MySQL-Sandbox to 3.0.43

diff --git a/zsh/bin/MySQL-Sandbox/bin/make_replication_sandbox b/zsh/bin/MySQL-Sandbox/bin/make_replication_sandbox
--- a/zsh/bin/MySQL-Sandbox/bin/make_replication_sandbox
+++ b/zsh/bin/MySQL-Sandbox/bin/make_replication_sandbox
@@ -123,6 +123,7 @@ for my $opt (qw(repl_user repl_password remote_access)) {
 
 my $base_version ;
 my $release_no;
+my $create_gtid_script=0;
 my $dashed_version ;
 my $replication_port = 0;
 my $prefix='';
@@ -138,6 +139,13 @@ if ( $temp_path =~ /(\d+)\.(\d+)\.(\d+)/ ) {
     $dashed_version = "${prefix}${major}_${minor}_${rev}";
     $base_version =~ s/^0+//;
     $base_version += $major + ($minor * 10) + ($rev * 100);
+    if (    ($major > 5)    # MySQL 6
+        or (($major == 5) && ($minor == 6) && ($rev >= 9 ))  #MySQL 5.6.9 and newer
+        or (( $major == 5) && ($minor > 6))  # MySQL 5.7 and newer
+       )
+    {
+        $create_gtid_script=1;
+    } 
 }
 else {
     $msb->get_help("No recognizable version pattern in $msb->{options}{server_version}\n");
@@ -148,6 +156,9 @@ my @supported_topologies = qw(standard circular);
 # deals with circular replication
 #
 
+my $node_list_text = 'master';
+my @node_list = ('master');
+
 if ($msb->{options}{master_master}) {
     $msb->{options}{topology} = 'circular';
     $msb->{options}{how_many_slaves} = 2;
@@ -156,6 +167,18 @@ if ($msb->{options}{master_master}) {
 if ($msb->{options}{circular} && ($msb->{options}{circular} =~ /^\d+$/)) {
     $msb->{options}{topology} = 'circular';
     $msb->{options}{how_many_slaves} = $msb->{options}{circular};
+}
+
+if ($msb->{options}{topology} eq 'circular')
+{
+    $node_list_text = '';
+    @node_list = ();
+}
+
+for my $n (1 .. $msb->{options}{how_many_slaves})
+{
+    $node_list_text .= " node$n";
+    push @node_list, "node$n";
 }
 
 if ($msb->{options}{'topology'} ) {
@@ -311,6 +334,7 @@ chdir $replication_directory;
 for my $cmd ( qw(start stop clear send_kill ) ) {
     my $cmd_fname = $cmd . '_all';
     $msb->write_to($cmd_fname, '>', '#!/bin/sh');
+    $msb->write_to($cmd_fname, '>>', qq(echo '# executing "$cmd"' on $replication_directory));
     if ($cmd eq 'start') {
         $msb->write_to ($cmd_fname, '>>', qq(echo 'executing "$cmd" on master') );
         $msb->write_to ($cmd_fname, '>>', qq($replication_directory/master/$cmd "\$@") );
@@ -340,7 +364,6 @@ if ( ( -x $mysql_proxy ) &&  ( -f $rw_splitting) ) {
     $msb->write_to('run_proxy',  '>>', "  --proxy-lua-script=$rw_splitting" ); 
     chmod 0755, 'run_proxy';
 }
-
 $msb->write_to('clear_all', '>>', "date > $replication_directory/needs_initialization");
 
 $msb->write_to('start_all', '>>', "if [ -f $replication_directory/needs_initialization ] ");
@@ -392,6 +415,9 @@ chmod 0755, 'status_all';
 
 
 $msb->write_to('check_slaves', '>', '#!/bin/sh' );
+$msb->write_to('check_slaves', '>>', '  echo "master"');
+$msb->write_to('check_slaves', '>>', "  $replication_directory/master/use -e "
+            . qq( 'show master status\\G' | grep "File\\|Position" ));
 $msb->write_to('check_slaves', '>>', 'for NNUM in ' . $slave_list );
 $msb->write_to('check_slaves', '>>', 'do' );
 $msb->write_to('check_slaves', '>>', '  echo "slave # $NNUM"');
@@ -419,16 +445,17 @@ for my $slave (1 .. $msb->{options}{how_many_slaves} ) {
     $msb->write_to('initialize_slaves', '>>', qq(echo "initializing slave $slave"));
 
     $msb->write_to('initialize_slaves', '>>',  
-      qq( echo 'CHANGE MASTER TO )
+             qq(echo 'CHANGE MASTER TO )
            . qq( master_host="127.0.0.1", )
            . qq( master_port=$replication_port, )
            . qq( master_user="$MySQL::Sandbox::default_users{'repl_user'}", )
            . qq( master_password="$MySQL::Sandbox::default_users{'repl_password'}" )
-           . qq(' | $replication_directory/node$slave/use -u root --password= ) );
+           . qq(' | $replication_directory/node$slave/use -u root  ) );
 
     $msb->write_to('initialize_slaves', '>>', 
             qq( echo 'START SLAVE' )
-           . qq( | $replication_directory/node$slave/use -u root --password= ) );
+           . qq( | $replication_directory/node$slave/use -u root ) );
+    system "perl -i -pe 's/^password/#password/' ./node$slave/my.sandbox.cnf"
 }
 
 #
@@ -440,6 +467,7 @@ for my $slave (1 .. $msb->{options}{how_many_slaves} ) {
 ##        and die "can't create slave user";
 
 chmod 0755, "initialize_slaves";
+
 system "./initialize_slaves"
         and die "can't initialize slave";
 
@@ -447,8 +475,21 @@ system "./initialize_slaves"
 # For the first run, there is root without password. 
 # After the first run, a password is assigned
 #
-system q( perl -i -pe 's/(-u root) (--password=)/$1/g' initialize_slaves );
+for my $slave (1 .. $msb->{options}{how_many_slaves} ) {
+    system "perl -i -pe 's/^#password/password/' ./node$slave/my.sandbox.cnf"
+}
+# system q( perl -i -pe 's/(-u root) (--password=)/$1/g' initialize_slaves );
 
+post_installation($replication_directory);
+$msb->write_to('README', '>', MySQL::Sandbox::Scripts::get_readme_master_slave());
+$msb->write_to('README', '>>', MySQL::Sandbox::Scripts::get_readme_common_replication());
+$msb->write_to('README', '>>', MySQL::Sandbox::Scripts::get_readme_common());
+
+for my $json (qw(connection.json default_connection.json))
+{
+    my $json_text = MySQL::Sandbox::get_json_from_dirs(\@node_list, $json);
+    $msb->write_to($json, '>', $json_text);
+}
 chdir $current_dir;
 print "replication directory installed in ", use_env($replication_directory), "\n";
 
@@ -460,22 +501,74 @@ sbinstr( "replication_directory installed in  <"
 
 sub make_circular_replication {
     my $cmd =  "make_multiple_sandbox --circular";
+    my $group_dir = 'rcsandbox_' . $dashed_version;
+    if ($msb->{options}{replication_directory} ) {
+        $group_dir = $msb->{options}{replication_directory};
+    }        
+
     if ($msb->{options}{how_many_slaves}) {
         $cmd .= ' --how_many_nodes=' . $msb->{options}{how_many_slaves};
     }
-    if ($msb->{options}{replication_directory} ) {
-        $cmd .= ' --group_directory=' . $msb->{options}{replication_directory};
-    }        
-    else {
-        $cmd .= ' --group_directory=rcsandbox_' . $dashed_version 
-    }
+    $cmd .= ' --group_directory=' . $group_dir; 
     if ($msb->{options}{sandbox_base_port} ) {
         $cmd .= ' --sandbox_base_port=' . $msb->{options}{sandbox_base_port}
     }
     else {
         $cmd .= ' --sandbox_base_port=' . ($defaults{circular_base_port} + ($release_no * 100));
     }
-    exec "$cmd $msb->{options}{server_version}" ;
+    my $result = system "$cmd $msb->{options}{server_version}" ;
+
+    post_installation("$msb->{options}{upper_directory}/$group_dir") unless $result;
+    exit $result;
+}
+
+sub post_installation
+{
+    my ($replication_directory) = @_;
+    # print "++ post_installation: <$replication_directory> <$node_list_text> <$create_gtid_script>\n";
+    unless (-d $replication_directory)
+    {
+        die "Error in post_installation procedure. $replication_directory not found\n";
+    }
+    chdir $replication_directory;
+
+my $gtid_script_template=<<'END_TEMPLATE';
+#!/bin/bash
+cd _REPLICATION_DIR_
+OPTIONS="master-info-repository=table "
+OPTIONS="$OPTIONS relay-log-info-repository=table"
+OPTIONS="$OPTIONS gtid_mode=ON"
+OPTIONS="$OPTIONS log-slave-updates enforce-gtid-consistency"
+CHANGED=""
+for NODE in _NODE_LIST_
+do
+    for OPTION in $OPTIONS
+    do
+        option_exists=$(grep $OPTION $NODE/my.sandbox.cnf)
+        if [ -z "$option_exists" ]
+        then
+            echo "$OPTION" >> $NODE/my.sandbox.cnf
+            echo "# option '$OPTION' added to $NODE configuration file"
+            CHANGED=1
+        else
+            echo "# option '$OPTION' already exists in $NODE configuration file"
+        fi
+    done
+done
+if [ -n "$CHANGED" ]
+then
+    ./restart_all
+fi
+END_TEMPLATE
+
+    if ($create_gtid_script)
+    {
+        $gtid_script_template =~ s/_REPLICATION_DIR_/$replication_directory/;
+        $gtid_script_template =~ s/_NODE_LIST_/$node_list_text/;
+        $msb->write_to('enable_gtid', '>', $gtid_script_template);
+        chmod 0755, 'enable_gtid';
+    }
+    
 }
 
 __END__
