Upgrade Percona Toolkit to 2.1.2

diff --git a/zsh/bin/percona-toolkit/bin/pt-mext b/zsh/bin/percona-toolkit/bin/pt-mext
--- a/zsh/bin/percona-toolkit/bin/pt-mext
+++ b/zsh/bin/percona-toolkit/bin/pt-mext
@@ -26,29 +26,32 @@ fi
 # See https://launchpad.net/percona-toolkit for more information.
 # ###########################################################################
 
-TMPDIR=""
+
+set -u
+
+PT_TMPDIR=""
 
 mk_tmpdir() {
-   local dir=${1:-""}
+   local dir="${1:-""}"
 
    if [ -n "$dir" ]; then
       if [ ! -d "$dir" ]; then
-         mkdir $dir || die "Cannot make tmpdir $dir"
+         mkdir "$dir" || die "Cannot make tmpdir $dir"
       fi
-      TMPDIR="$dir"
+      PT_TMPDIR="$dir"
    else
-      local tool=`basename $0`
+      local tool="${0##*/}"
       local pid="$$"
-      TMPDIR=`mktemp -d /tmp/${tool}.${pid}.XXXXX` \
+      PT_TMPDIR=`mktemp -d -t "${tool}.${pid}.XXXXXX"` \
          || die "Cannot make secure tmpdir"
    fi
 }
 
 rm_tmpdir() {
-   if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]; then
-      rm -rf $TMPDIR
+   if [ -n "$PT_TMPDIR" ] && [ -d "$PT_TMPDIR" ]; then
+      rm -rf "$PT_TMPDIR"
    fi
-   TMPDIR=""
+   PT_TMPDIR=""
 }
 
 # ###########################################################################
@@ -57,7 +60,7 @@ rm_tmpdir() {
 
 mk_tmpdir
 
-FILE="$TMPDIR/mext_temp_file";
+FILE="$PT_TMPDIR/mext_temp_file";
 NUM=0;
 REL=0;
 
@@ -279,7 +282,7 @@ Place, Suite 330, Boston, MA  02111-1307  USA.
 
 =head1 VERSION
 
-pt-mext 2.1.1
+pt-mext 2.1.2
 
 =cut
 
diff --git a/zsh/bin/percona-toolkit/bin/pt-mysql-summary b/zsh/bin/percona-toolkit/bin/pt-mysql-summary
--- a/zsh/bin/percona-toolkit/bin/pt-mysql-summary
+++ b/zsh/bin/percona-toolkit/bin/pt-mysql-summary
@@ -155,7 +155,7 @@ parse_options() {
    OPT_ERRS=0
    OPT_VERSION=""
    OPT_HELP=""
-   PO_DIR="$TMPDIR/po"
+   PO_DIR="$PT_TMPDIR/po"
 
    if [ ! -d "$PO_DIR" ]; then
       mkdir "$PO_DIR"
@@ -359,10 +359,10 @@ _parse_command_line() {
             opt="$(echo $opt | awk -F= '{print $1}')"
          fi
 
-         if [ -f "$TMPDIR/po/$opt" ]; then
-            spec="$TMPDIR/po/$opt"
+         if [ -f "$PT_TMPDIR/po/$opt" ]; then
+            spec="$PT_TMPDIR/po/$opt"
          else
-            spec=$(grep "^short form:-$opt\$" "$TMPDIR"/po/* | cut -d ':' -f 1)
+            spec=$(grep "^short form:-$opt\$" "$PT_TMPDIR"/po/* | cut -d ':' -f 1)
             if [ -z "$spec"  ]; then
                option_error "Unknown option: $real_opt"
                continue
@@ -432,7 +432,7 @@ size_to_bytes() {
 
 set -u
 
-TMPDIR=""
+PT_TMPDIR=""
 
 mk_tmpdir() {
    local dir="${1:-""}"
@@ -441,20 +441,20 @@ mk_tmpdir() {
       if [ ! -d "$dir" ]; then
          mkdir "$dir" || die "Cannot make tmpdir $dir"
       fi
-      TMPDIR="$dir"
+      PT_TMPDIR="$dir"
    else
       local tool="${0##*/}"
       local pid="$$"
-      TMPDIR=`mktemp -d /tmp/${tool}.${pid}.XXXXX` \
+      PT_TMPDIR=`mktemp -d -t "${tool}.${pid}.XXXXXX"` \
          || die "Cannot make secure tmpdir"
    fi
 }
 
 rm_tmpdir() {
-   if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]; then
-      rm -rf "$TMPDIR"
+   if [ -n "$PT_TMPDIR" ] && [ -d "$PT_TMPDIR" ]; then
+      rm -rf "$PT_TMPDIR"
    fi
-   TMPDIR=""
+   PT_TMPDIR=""
 }
 
 # ###########################################################################
@@ -576,22 +576,19 @@ shorten() {
    local div="${3:-1024}"
 
    echo "$num" | awk -v prec="$prec" -v div="$div" '
-   {
-      size = 4;
-      val  = $1;
-
-      unit = val >= 1099511627776 ? "T" : val >= 1073741824 ? "G" : val >= 1048576 ? "M" : val >= 1024 ? "k" : "";
-
-      while ( int(val) && !(val % 1024) ) {
-         val /= 1024;
+      {
+         num  = $1;
+         unit = num >= 1125899906842624 ? "P" \
+              : num >= 1099511627776    ? "T" \
+              : num >= 1073741824       ? "G" \
+              : num >= 1048576          ? "M" \
+              : num >= 1024             ? "k" \
+              :                           "";
+         while ( num >= div ) {
+            num /= div;
+         }
+         printf "%.*f%s", prec, num, unit;
       }
-
-      while ( val > 1000 ) {
-         val /= div;
-      }
-
-      printf "%.*f%s", prec, val, unit;
-   }
    '
 }
 
@@ -626,7 +623,7 @@ get_nice_of_pid () {
    if [ -n "${niceness}" ]; then
       echo $niceness
    else
-      local tmpfile="$TMPDIR/nice_through_c.tmp.c"
+      local tmpfile="$PT_TMPDIR/nice_through_c.tmp.c"
       _d "Getting the niceness from ps failed, somehow. We are about to try this:"
       cat <<EOC > "$tmpfile"
 
@@ -708,8 +705,8 @@ setup_data_dir () {
    local existing_dir="$1"
    local data_dir=""
    if [ -z "$existing_dir" ]; then
-      mkdir "$TMPDIR/data" || die "Cannot mkdir $TMPDIR/data"
-      data_dir="$TMPDIR/data"
+      mkdir "$PT_TMPDIR/data" || die "Cannot mkdir $PT_TMPDIR/data"
+      data_dir="$PT_TMPDIR/data"
    else
       if [ ! -d "$existing_dir" ]; then
          mkdir "$existing_dir" || die "Cannot mkdir $existing_dir"
@@ -761,6 +758,7 @@ collect_mysqld_instances () {
          echo "internal::oom_of_$pid    $oom" >> "$variables_file"
       done
 
+      pids="$pids"
       pids="$(echo $pids | sed -e 's/ /,/g')"
       ps ww -p "$pids" 2>/dev/null
    else
@@ -838,8 +836,8 @@ collect_master_logs_status () {
 
 collect_mysql_deferred_status () {
    local status_file="$1"
-   collect_mysql_status > "$TMPDIR/defer_gatherer"
-   join "$status_file" "$TMPDIR/defer_gatherer"
+   collect_mysql_status > "$PT_TMPDIR/defer_gatherer"
+   join "$status_file" "$PT_TMPDIR/defer_gatherer"
 }
 
 collect_internal_vars () {
@@ -1389,7 +1387,7 @@ find_max_trx_time() {
 
 find_transation_states () {
    local file="$1"
-   local tmpfile="$TMPDIR/find_transation_states.tmp"
+   local tmpfile="$PT_TMPDIR/find_transation_states.tmp"
 
    [ -e "$file" ] || return
 
@@ -1440,7 +1438,7 @@ format_innodb_status () {
 
 format_overall_db_stats () {
    local file="$1"
-   local tmpfile="$TMPDIR/format_overall_db_stats.tmp"
+   local tmpfile="$PT_TMPDIR/format_overall_db_stats.tmp"
 
    [ -e "$file" ] || return
 
@@ -1794,7 +1792,7 @@ section_innodb () {
    local log_file="$(get_var innodb_log_files_in_group "$variables_file")"
    local log_total=$(awk "BEGIN {printf \"%.2f\n\", ${log_size}*${log_file}}" )
    name_val "Log File Size"       \
-            "${log_file} * $(shorten ${log_size} 1 1000) = $(shorten ${log_total} 1 1000)"
+            "${log_file} * $(shorten ${log_size} 1) = $(shorten ${log_total} 1)"
    name_val "Log Buffer Size"     \
             "$(shorten $(get_var innodb_log_buffer_size "$variables_file") 0)"
    name_val "Flush Method"        \
@@ -2854,7 +2852,7 @@ Replace C<TOOL> with the name of any tool.
 
 =head1 AUTHORS
 
-Baron Schwartz, Brian Fraser, and Daniel Nichter.
+Baron Schwartz, Brian Fraser, and Daniel Nichter
 
 =head1 ABOUT PERCONA TOOLKIT
 
@@ -2886,7 +2884,7 @@ Place, Suite 330, Boston, MA  02111-1307  USA.
 
 =head1 VERSION
 
-pt-mysql-summary 2.1.1
+pt-mysql-summary 2.1.2
 
 =cut
 
diff --git a/zsh/bin/percona-toolkit/bin/pt-sift b/zsh/bin/percona-toolkit/bin/pt-sift
--- a/zsh/bin/percona-toolkit/bin/pt-sift
+++ b/zsh/bin/percona-toolkit/bin/pt-sift
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+TOOL="pt-sift"
+
 # This program is part of Percona Toolkit: http://www.percona.com/software/
 # See "COPYRIGHT, LICENSE, AND WARRANTY" at the end of this file for legal
 # notices and disclaimers.
@@ -22,32 +24,32 @@ usage() {
 # See https://launchpad.net/percona-toolkit for more information.
 # ###########################################################################
 
-# pt-sift isn't ready for this yet.
-#set -u
 
-TMPDIR=""
+set -u
+
+PT_TMPDIR=""
 
 mk_tmpdir() {
-   local dir=${1:-""}
+   local dir="${1:-""}"
 
    if [ -n "$dir" ]; then
       if [ ! -d "$dir" ]; then
-         mkdir $dir || die "Cannot make tmpdir $dir"
+         mkdir "$dir" || die "Cannot make tmpdir $dir"
       fi
-      TMPDIR="$dir"
+      PT_TMPDIR="$dir"
    else
-      local tool=`basename $0`
+      local tool="${0##*/}"
       local pid="$$"
-      TMPDIR=`mktemp -d /tmp/${tool}.${pid}.XXXXX` \
+      PT_TMPDIR=`mktemp -d -t "${tool}.${pid}.XXXXXX"` \
          || die "Cannot make secure tmpdir"
    fi
 }
 
 rm_tmpdir() {
-   if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]; then
-      rm -rf $TMPDIR
+   if [ -n "$PT_TMPDIR" ] && [ -d "$PT_TMPDIR" ]; then
+      rm -rf "$PT_TMPDIR"
    fi
-   TMPDIR=""
+   PT_TMPDIR=""
 }
 
 # ###########################################################################
@@ -118,17 +120,17 @@ main() {
 
    # We need to generate a list of timestamps, and ask the user to choose one if
    # there is no PREFIX yet.  NOTE: we rely on the "-df" files here.
-   ls "${BASEDIR}" | grep -- '-df$' | cut -d- -f1 | sort > $TMPDIR/pt-sift.prefixes
+   ls "${BASEDIR}" | grep -- '-df$' | cut -d- -f1 | sort > $PT_TMPDIR/pt-sift.prefixes
    if [ -z "${PREFIX}" ]; then
-      if [ "$(grep -c . $TMPDIR/pt-sift.prefixes)" = "1" ]; then
+      if [ "$(grep -c . $PT_TMPDIR/pt-sift.prefixes)" = "1" ]; then
          # If there is only one sample, we use it as the prefix.
-         PREFIX="$(cat $TMPDIR/pt-sift.prefixes)"
+         PREFIX="$(cat $PT_TMPDIR/pt-sift.prefixes)"
       fi
    fi
    if [ -z "${PREFIX}" ]; then
       echo
       i=0
-      cat $TMPDIR/pt-sift.prefixes | while read line; do
+      cat $PT_TMPDIR/pt-sift.prefixes | while read line; do
          i=$(($i + 1))
          echo -n "  $line"
          if [ "${i}" = "3" ]; then
@@ -138,14 +140,14 @@ main() {
       done
       # We might have ended mid-line or we might have printed a newline; print a
       # newline if required to end the list of timestamp prefixes.
-      awk 'BEGIN { i = 0 } { i++ } END { if ( i % 3 != 0 ) { print "" } }' $TMPDIR/pt-sift.prefixes
+      awk 'BEGIN { i = 0 } { i++ } END { if ( i % 3 != 0 ) { print "" } }' $PT_TMPDIR/pt-sift.prefixes
       echo
-      while [ -z "${PREFIX}" -o "$(grep -c "${PREFIX}" $TMPDIR/pt-sift.prefixes)" -ne 1 ]; do
-         DEFAULT="$(tail -1 $TMPDIR/pt-sift.prefixes)"
+      while [ -z "${PREFIX}" -o "$(grep -c "${PREFIX}" $PT_TMPDIR/pt-sift.prefixes)" -ne 1 ]; do
+         DEFAULT="$(tail -1 $PT_TMPDIR/pt-sift.prefixes)"
          read -e -p "Select a timestamp from the list [${DEFAULT}] " ARG
          ARG="${ARG:-${DEFAULT}}"
-         if [ "$(grep -c "${ARG}" $TMPDIR/pt-sift.prefixes)" -eq 1 ]; then
-            PREFIX="$(grep "${ARG}" $TMPDIR/pt-sift.prefixes)"
+         if [ "$(grep -c "${ARG}" $PT_TMPDIR/pt-sift.prefixes)" -eq 1 ]; then
+            PREFIX="$(grep "${ARG}" $PT_TMPDIR/pt-sift.prefixes)"
          fi
       done
    fi
@@ -157,7 +159,7 @@ main() {
       if [ "${ACTION}" != "INVALID" ]; then
          # Print the current host, timestamp and action.  Figure out if we're at
          # the first or last sample, to make it easy to navigate.
-         PAGE="$(awk "/./{i++} /${PREFIX}/{c=i} END{print c, \"of\", i}" $TMPDIR/pt-sift.prefixes)"
+         PAGE="$(awk "/./{i++} /${PREFIX}/{c=i} END{print c, \"of\", i}" $PT_TMPDIR/pt-sift.prefixes)"
          HOST="$(cat "${BASEDIR}/${PREFIX}-hostname" 2>/dev/null)"
          echo -e "======== ${HOST:-unknown} at \033[34m${PREFIX} \033[31m${ACTION}\033[0m (${PAGE}) ========"
       fi
@@ -494,7 +496,7 @@ main() {
                   if ( printed == 0 ) {
                      print \"${PREFIX}\";
                   }
-               }" $TMPDIR/pt-sift.prefixes)"
+               }" $PT_TMPDIR/pt-sift.prefixes)"
             ;;
          1)
             ACTION="DEFAULT"
@@ -536,7 +538,8 @@ main() {
 
 # Execute the program if it was not included from another file.  This makes it
 # possible to include without executing, and thus test.
-if [ "$(basename "$0")" = "pt-sift" ] || [ "$(basename "$0")" = "bash" -a "$_" = "$0" ]; then
+if    [ "${0##*/}" = "$TOOL" ] \
+   || [ "${0##*/}" = "bash" -a "$_" = "$0" ]; then
     main "$@"
 fi
 
@@ -726,7 +729,7 @@ Place, Suite 330, Boston, MA  02111-1307  USA.
 
 =head1 VERSION
 
-pt-sift 2.1.1
+pt-sift 2.1.2
 
 =cut
 
diff --git a/zsh/bin/percona-toolkit/bin/pt-summary b/zsh/bin/percona-toolkit/bin/pt-summary
--- a/zsh/bin/percona-toolkit/bin/pt-summary
+++ b/zsh/bin/percona-toolkit/bin/pt-summary
@@ -162,7 +162,7 @@ parse_options() {
    OPT_ERRS=0
    OPT_VERSION=""
    OPT_HELP=""
-   PO_DIR="$TMPDIR/po"
+   PO_DIR="$PT_TMPDIR/po"
 
    if [ ! -d "$PO_DIR" ]; then
       mkdir "$PO_DIR"
@@ -366,10 +366,10 @@ _parse_command_line() {
             opt="$(echo $opt | awk -F= '{print $1}')"
          fi
 
-         if [ -f "$TMPDIR/po/$opt" ]; then
-            spec="$TMPDIR/po/$opt"
+         if [ -f "$PT_TMPDIR/po/$opt" ]; then
+            spec="$PT_TMPDIR/po/$opt"
          else
-            spec=$(grep "^short form:-$opt\$" "$TMPDIR"/po/* | cut -d ':' -f 1)
+            spec=$(grep "^short form:-$opt\$" "$PT_TMPDIR"/po/* | cut -d ':' -f 1)
             if [ -z "$spec"  ]; then
                option_error "Unknown option: $real_opt"
                continue
@@ -439,7 +439,7 @@ size_to_bytes() {
 
 set -u
 
-TMPDIR=""
+PT_TMPDIR=""
 
 mk_tmpdir() {
    local dir="${1:-""}"
@@ -448,20 +448,20 @@ mk_tmpdir() {
       if [ ! -d "$dir" ]; then
          mkdir "$dir" || die "Cannot make tmpdir $dir"
       fi
-      TMPDIR="$dir"
+      PT_TMPDIR="$dir"
    else
       local tool="${0##*/}"
       local pid="$$"
-      TMPDIR=`mktemp -d /tmp/${tool}.${pid}.XXXXX` \
+      PT_TMPDIR=`mktemp -d -t "${tool}.${pid}.XXXXXX"` \
          || die "Cannot make secure tmpdir"
    fi
 }
 
 rm_tmpdir() {
-   if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]; then
-      rm -rf "$TMPDIR"
+   if [ -n "$PT_TMPDIR" ] && [ -d "$PT_TMPDIR" ]; then
+      rm -rf "$PT_TMPDIR"
    fi
-   TMPDIR=""
+   PT_TMPDIR=""
 }
 
 # ###########################################################################
@@ -538,7 +538,7 @@ get_nice_of_pid () {
    if [ -n "${niceness}" ]; then
       echo $niceness
    else
-      local tmpfile="$TMPDIR/nice_through_c.tmp.c"
+      local tmpfile="$PT_TMPDIR/nice_through_c.tmp.c"
       _d "Getting the niceness from ps failed, somehow. We are about to try this:"
       cat <<EOC > "$tmpfile"
 
@@ -620,8 +620,8 @@ setup_data_dir () {
    local existing_dir="$1"
    local data_dir=""
    if [ -z "$existing_dir" ]; then
-      mkdir "$TMPDIR/data" || die "Cannot mkdir $TMPDIR/data"
-      data_dir="$TMPDIR/data"
+      mkdir "$PT_TMPDIR/data" || die "Cannot mkdir $PT_TMPDIR/data"
+      data_dir="$PT_TMPDIR/data"
    else
       if [ ! -d "$existing_dir" ]; then
          mkdir "$existing_dir" || die "Cannot mkdir $existing_dir"
@@ -713,22 +713,19 @@ shorten() {
    local div="${3:-1024}"
 
    echo "$num" | awk -v prec="$prec" -v div="$div" '
-   {
-      size = 4;
-      val  = $1;
-
-      unit = val >= 1099511627776 ? "T" : val >= 1073741824 ? "G" : val >= 1048576 ? "M" : val >= 1024 ? "k" : "";
-
-      while ( int(val) && !(val % 1024) ) {
-         val /= 1024;
+      {
+         num  = $1;
+         unit = num >= 1125899906842624 ? "P" \
+              : num >= 1099511627776    ? "T" \
+              : num >= 1073741824       ? "G" \
+              : num >= 1048576          ? "M" \
+              : num >= 1024             ? "k" \
+              :                           "";
+         while ( num >= div ) {
+            num /= div;
+         }
+         printf "%.*f%s", prec, num, unit;
       }
-
-      while ( val > 1000 ) {
-         val /= div;
-      }
-
-      printf "%.*f%s", prec, val, unit;
-   }
    '
 }
 
@@ -862,17 +859,19 @@ linux_exclusive_collection () { local PTFUNCNAME=linux_exclusive_collection;
    [ "$CMD_GETENFORCE" ] && getenforce="$($CMD_GETENFORCE 2>&1)"
    echo "getenforce    ${getenforce:-"No SELinux detected"}" >> "$data_dir/summary"
 
-   echo "swappiness    $(awk '/vm.swappiness/{print $3}' "$data_dir/sysctl")" >> "$data_dir/summary"
+   if [ -e "$data_dir/sysctl" ]; then
+      echo "swappiness    $(awk '/vm.swappiness/{print $3}' "$data_dir/sysctl")" >> "$data_dir/summary"
 
-   local dirty_ratio="$(awk '/vm.dirty_ratio/{print $3}' "$data_dir/sysctl")"
-   local dirty_bg_ratio="$(awk '/vm.dirty_background_ratio/{print $3}' "$data_dir/sysctl")"
-   if [ "$dirty_ratio" -a "$dirty_bg_ratio" ]; then
-      echo "dirtypolicy    $dirty_ratio, $dirty_bg_ratio" >> "$data_dir/summary"
-   fi
+      local dirty_ratio="$(awk '/vm.dirty_ratio/{print $3}' "$data_dir/sysctl")"
+      local dirty_bg_ratio="$(awk '/vm.dirty_background_ratio/{print $3}' "$data_dir/sysctl")"
+      if [ "$dirty_ratio" -a "$dirty_bg_ratio" ]; then
+         echo "dirtypolicy    $dirty_ratio, $dirty_bg_ratio" >> "$data_dir/summary"
+      fi
 
-   local dirty_bytes="$(awk '/vm.dirty_bytes/{print $3}' "$data_dir/sysctl")"
-   if [ "$dirty_bytes" ]; then
-      echo "dirtystatus     $(awk '/vm.dirty_bytes/{print $3}' "$data_dir/sysctl"), $(awk '/vm.dirty_background_bytes/{print $3}' "$data_dir/sysctl")" >> "$data_dir/summary"
+      local dirty_bytes="$(awk '/vm.dirty_bytes/{print $3}' "$data_dir/sysctl")"
+      if [ "$dirty_bytes" ]; then
+         echo "dirtystatus     $(awk '/vm.dirty_bytes/{print $3}' "$data_dir/sysctl"), $(awk '/vm.dirty_background_bytes/{print $3}' "$data_dir/sysctl")" >> "$data_dir/summary"
+      fi
    fi
 
    schedulers_and_queue_size "$data_dir/summary" > "$data_dir/partitioning"
@@ -894,7 +893,7 @@ network_device_info () {
    local ip_minus_s_file="$1"
 
    if [ "$CMD_ETHTOOL" ]; then
-      local tempfile="$TMPDIR/ethtool_output_temp"
+      local tempfile="$PT_TMPDIR/ethtool_output_temp"
       for device in $( awk '/^[1-9]/{ print $2 }'  "$ip_minus_s_file" \
                         | awk -F: '{print $1}'     \
                         | grep -v '^lo\|^in\|^gr'  \
@@ -997,7 +996,7 @@ find_virtualization () { local PTFUNCNAME=find_virtualization;
    local dmesg_file="$2"
    local lspci_file="$3"
 
-   local tempfile="$TMPDIR/find_virtualziation.tmp"
+   local tempfile="$PT_TMPDIR/find_virtualziation.tmp"
 
    local virt=""
    if [ -s "$dmesg_file" ]; then
@@ -1087,8 +1086,8 @@ mounted_fs_info () { local PTFUNCNAME=mounted_fs_info;
       if [ "${platform}" = "Linux" ]; then
          cmd="df -h -P"
       fi
-      $cmd  | sort > "$TMPDIR/mounted_fs_info.tmp"
-      mount | sort | join "$TMPDIR/mounted_fs_info.tmp" -
+      $cmd  | sort > "$PT_TMPDIR/mounted_fs_info.tmp"
+      mount | sort | join "$PT_TMPDIR/mounted_fs_info.tmp" -
    fi
 }
 
@@ -1096,7 +1095,7 @@ raid_controller () { local PTFUNCNAME=raid_controller;
    local dmesg_file="$1"
    local lspci_file="$2"
 
-   local tempfile="$TMPDIR/raid_controller.tmp"
+   local tempfile="$PT_TMPDIR/raid_controller.tmp"
 
    local controller=""
    if [ -s "$lspci_file" ]; then
@@ -1274,16 +1273,16 @@ parse_proc_cpuinfo () { local PTFUNCNAME=parse_proc_cpuinfo;
    name_val "Processors" "physical = ${physical}, cores = ${cores}, virtual = ${virtual}, hyperthreading = ${htt}"
 
    awk -F: '/cpu MHz/{print $2}' "${file}" \
-      | sort | uniq -c > "$TMPDIR/parse_proc_cpuinfo_cpu.unq"
-   name_val "Speeds" "$(group_concat "$TMPDIR/parse_proc_cpuinfo_cpu.unq")"
+      | sort | uniq -c > "$PT_TMPDIR/parse_proc_cpuinfo_cpu.unq"
+   name_val "Speeds" "$(group_concat "$PT_TMPDIR/parse_proc_cpuinfo_cpu.unq")"
 
    awk -F: '/model name/{print $2}' "${file}" \
-      | sort | uniq -c > "$TMPDIR/parse_proc_cpuinfo_model.unq"
-   name_val "Models" "$(group_concat "$TMPDIR/parse_proc_cpuinfo_model.unq")"
+      | sort | uniq -c > "$PT_TMPDIR/parse_proc_cpuinfo_model.unq"
+   name_val "Models" "$(group_concat "$PT_TMPDIR/parse_proc_cpuinfo_model.unq")"
 
    awk -F: '/cache size/{print $2}' "${file}" \
-      | sort | uniq -c > "$TMPDIR/parse_proc_cpuinfo_cache.unq"
-   name_val "Caches" "$(group_concat "$TMPDIR/parse_proc_cpuinfo_cache.unq")"
+      | sort | uniq -c > "$PT_TMPDIR/parse_proc_cpuinfo_cache.unq"
+   name_val "Caches" "$(group_concat "$PT_TMPDIR/parse_proc_cpuinfo_cache.unq")"
 }
 
 parse_sysctl_cpu_freebsd() { local PTFUNCNAME=parse_sysctl_cpu_freebsd;
@@ -1325,8 +1324,8 @@ parse_psrinfo_cpus() { local PTFUNCNAME=parse_psrinfo_cpus;
       start = index($0, " at ") + 4;
       end   = length($0) - start - 4
       print substr($0, start, end);
-   }' "$file" | sort | uniq -c > "$TMPDIR/parse_psrinfo_cpus.tmp"
-   name_val "Speeds" "$(group_concat "$TMPDIR/parse_psrinfo_cpus.tmp")"
+   }' "$file" | sort | uniq -c > "$PT_TMPDIR/parse_psrinfo_cpus.tmp"
+   name_val "Speeds" "$(group_concat "$PT_TMPDIR/parse_psrinfo_cpus.tmp")"
 }
 
 parse_free_minus_b () { local PTFUNCNAME=parse_free_minus_b;
@@ -1378,7 +1377,7 @@ parse_memory_sysctl_netbsd() { local PTFUNCNAME=parse_memory_sysctl_netbsd;
 
    [ -e "$file" -a -e "$swapctl_file" ] || return
 
-   local swap_mem="$(echo "$(awk '{print $2;}' "$swapctl_file")*512" | bc -l)"
+   local swap_mem="$(awk '{print $2*512}' "$swapctl_file")"
    name_val "Total"   $(shorten "$(awk '/hw.physmem /{print $NF}' "$file")" 1)
    name_val "User"    $(shorten "$(awk '/hw.usermem /{print $NF}' "$file")" 1)
    name_val "Swap"    $(shorten ${swap_mem} 1)
@@ -1390,7 +1389,7 @@ parse_memory_sysctl_openbsd() { local PTFUNCNAME=parse_memory_sysctl_openbsd;
 
    [ -e "$file" -a -e "$swapctl_file" ] || return
 
-   local swap_mem="$(echo "$(awk '{print $2;}' "$swapctl_file")*512" | bc -l)"
+   local swap_mem="$(awk '{print $2*512}' "$swapctl_file")"
    name_val "Total"   $(shorten "$(awk -F= '/hw.physmem/{print $2}' "$file")" 1)
    name_val "User"    $(shorten "$(awk -F= '/hw.usermem/{print $2}' "$file")" 1)
    name_val "Swap"    $(shorten ${swap_mem} 1)
@@ -2527,7 +2526,7 @@ Replace C<TOOL> with the name of any tool.
 
 =head1 AUTHORS
 
-Baron Schwartz and Kevin van Zonneveld (http://kevin.vanzonneveld.net)
+Baron Schwartz, Kevin van Zonneveld, and Brian Fraser
 
 =head1 ABOUT PERCONA TOOLKIT
 
@@ -2559,7 +2558,7 @@ Place, Suite 330, Boston, MA  02111-1307  USA.
 
 =head1 VERSION
 
-pt-summary 2.1.1
+pt-summary 2.1.2
 
 =cut
 
